# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend Build Check

on:
  push:
    branches: [ "main", "Working" ] 
  pull_request:
    branches: [ "main", "Working" ]

jobs:
  backend-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build Backend
        run: npm run build --if-present
      - name: Test Backend
        run: npm run test --if-present
      - name: Syntax Check Backend
        run: 
          node --check Backend/server.js
